const sampleUsers = [
  {
    name: 'Admin User',
    email: 'admin@teamtask.local',
    password: 'admin123',
    role: 'admin',
  },
  {
    name: 'Member User',
    email: 'member@teamtask.local',
    password: 'member123',
    role: 'member',
  },
];

const sampleTeam = {
  name: 'Core Team',
  description: 'Initial team generated by seed command',
};

const sampleProject = {
  title: 'Platform Launch',
  description: 'Coordinate launch milestones, QA and go-live tasks',
  status: 'active',
};

const sampleTasks = [
  {
    title: 'Set up deployment pipeline',
    description: 'Configure CI/CD and environment variables for production deployment',
    priority: 'high',
    status: 'in-progress',
    dueInDays: 5,
  },
  {
    title: 'Write API integration tests',
    description: 'Cover authentication and task routes with happy and error paths',
    priority: 'medium',
    status: 'todo',
    dueInDays: 7,
  },
];

export {
  sampleUsers,
  sampleTeam,
  sampleProject,
  sampleTasks,
};
